# Generated by Django 5.2.3 on 2025-07-04 13:04

import chessbackend.models.game
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_start_time", models.DateTimeField(auto_now=True)),
                ("game_end_time", models.DateTimeField(blank=True, null=True)),
                ("initial_player_time", models.DurationField(blank=True, null=True)),
                ("white_remaining_time", models.DurationField(blank=True, null=True)),
                ("black_remaining_time", models.DurationField(blank=True, null=True)),
                ("time_increment", models.IntegerField(blank=True, null=True)),
                (
                    "starting_position",
                    models.CharField(
                        choices=[
                            ("standard", "STANDARD"),
                            ("fisher_random", "FISHER_RANDOM"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "current_board",
                    models.JSONField(default=chessbackend.models.game.default_board),
                ),
                ("game_history", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("black", "BLACK"), ("white", "WHITE")], max_length=25
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pawn", "PAWN"),
                            ("bishop", "BISHOP"),
                            ("knight", "KNIGHT"),
                            ("rook", "ROOK"),
                            ("queen", "QUEEN"),
                            ("king", "KING"),
                        ],
                        max_length=25,
                    ),
                ),
                ("starting_row", models.IntegerField()),
                ("starting_column", models.IntegerField()),
                ("current_row", models.IntegerField()),
                ("current_column", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="chessbackend.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("start_row", models.IntegerField(blank=True, null=True)),
                ("start_column", models.IntegerField(blank=True, null=True)),
                ("end_row", models.IntegerField(blank=True, null=True)),
                ("end_column", models.IntegerField(blank=True, null=True)),
                ("number", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="chessbackend.game",
                    ),
                ),
                (
                    "captured_piece",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capture_move",
                        to="chessbackend.piece",
                    ),
                ),
                (
                    "moving_piece",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moves",
                        to="chessbackend.piece",
                    ),
                ),
            ],
        ),
    ]
