# Generated by Django 5.2.4 on 2025-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chessbackend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="starting_position",
            field=models.CharField(
                choices=[("standard", "STANDARD"), ("fisher_random", "FISHER_RANDOM")],
                default="standard",
                max_length=25,
            ),
        ),
    ]
