# Generated by Django 5.2.4 on 2025-07-31 17:47

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='move',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='piece',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='move',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
