# Generated by Django 5.2.4 on 2025-07-21 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chessbackend", "0002_alter_game_starting_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="captured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="piece",
            name="captured_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captured_pieces",
                to="chessbackend.piece",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="current_board",
            field=models.JSONField(default=dict),
        ),
    ]
