# Generated by Django 5.2.4 on 2025-07-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chessbackend", "0003_piece_captured_piece_captured_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="move_color",
            field=models.CharField(
                choices=[("black", "BLACK"), ("white", "WHITE")],
                default="white",
                max_length=25,
            ),
            preserve_default=False,
        ),
    ]
