# Generated by Django 5.2.4 on 2025-07-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chessbackend", "0004_move_move_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="black_check_pieces",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="game",
            name="black_in_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="white_check_pieces",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="game",
            name="white_in_check",
            field=models.BooleanField(default=False),
        ),
    ]
