# Generated by Django 5.2.4 on 2025-07-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chessbackend", "0005_game_black_check_pieces_game_black_in_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="defended",
            field=models.BooleanField(default=False),
        ),
    ]
